overblog_graphql:
    batching_method: "apollo"
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"
    definitions:
        schema:
            default:
                query: Query
                mutation: Mutation
        mappings:
            auto_discover: false
            types:
                -
                    type: annotation
                    dir: "%kernel.project_dir%/src/Entity"
                    suffix: ~
                -
                    type: annotation
                    dir: "%kernel.project_dir%/src/GraphQL"
                    suffix: ~

overblog_dataloader:
    defaults:
        promise_adapter: 'overblog_dataloader.webonyx_graphql_sync_promise_adapter'
        options:
            batch: true
            cache: true
            max_batch_size: 50
            cache_map: 'overblog_dataloader.cache_map'
    loaders:
        category:
            alias: 'category_loader'
            batch_load_fn: '@App\GraphQL\Loader\CategoryLoader:all'