language: php

php:
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction
  - composer require "squizlabs/php_codesniffer=*"

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/grumphp run
  - ./vendor/bin/phpstan analyse
