version: "3"

services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: expense-tracker-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense-tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  php:
    image: snaksa/expense-tracker-backend
    build:
      context: .
    container_name: expense-tracker-backend
    environment:
      - DATABASE_URL=mysql://symfony:symfony@db:3306/expense-tracker?serverVersion=5.7
      - JWT_PASSPHRASE=expensestracker2020
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
