services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\EventListener\User\CreateListener:
        class: App\EventListener\User\CreateListener
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: App\Entity\User, lazy: true }

